### PR TITLE
Added responseBodyParser option to handle expect String

### PR DESCRIPTION
**Pull request by h-kishi**
In some case, we would like to handle a response expect for String.
For example, if a developer is using MessagePack, the response is byte array.
I added option to change the response body parser.

### CODE REVIEW

**Comment by krrrr38** [comment]
@h-kishi thanks a lot :bow: 
 If you need, I will publish next version asap. let me know.

**Comment by h-kishi** [comment]
@krrrr38 I would appreciate if you will publish next version soon.

**Comment by krrrr38** [comment]
@h-kishi 
Now, I just released 0.1.2-SNAPSHOT and 0.2.1-SNAPSHOT which include this feature.
For a while, please use them. Regards.

**Comment by h-kishi** [comment]
@krrrr38 Thanks :)

**Pull request merged**
